spring:
  application:
    name: javalearning
  redis:
    host: localhost
    port: 6379
#  security:
#    user:
#      name: user
#      password: password
#  mongodb:
#    host: localhost
#    port: 27017
#    database: javalearningdb
#  datasource:
#    url: jdbc:h2:file:/data/demo
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings.trace: false
#      settings.web-allow-others: false
#  security:
#    enabled: false
springdoc:
  swagger-ui:
    path: /docs

#2   3   4   5   2   3  720
#2   6   24  120 240 720
#
#720 360 120 30  6   3