/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.javalearning.person;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Person extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5914045506352907821L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Person\",\"namespace\":\"com.javalearning.person\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"age\",\"type\":\"int\"},{\"name\":\"height\",\"type\":\"float\"},{\"name\":\"isEmployed\",\"type\":\"boolean\"},{\"name\":\"address\",\"type\":\"string\"},{\"name\":\"phoneNumbers\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"salary\",\"type\":[\"null\",\"float\"],\"default\":null},{\"name\":\"birthDate\",\"type\":{\"type\":\"record\",\"name\":\"Date\",\"fields\":[{\"name\":\"year\",\"type\":\"int\"},{\"name\":\"month\",\"type\":\"int\"},{\"name\":\"day\",\"type\":\"int\"}]}},{\"name\":\"skills\",\"type\":{\"type\":\"map\",\"values\":\"string\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Person> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Person> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Person> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Person> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Person> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Person to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Person from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Person instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Person fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private int id;
  private java.lang.CharSequence name;
  private int age;
  private float height;
  private boolean isEmployed;
  private java.lang.CharSequence address;
  private java.util.List<java.lang.CharSequence> phoneNumbers;
  private java.lang.Float salary;
  private com.javalearning.person.Date birthDate;
  private java.util.Map<java.lang.CharSequence,java.lang.CharSequence> skills;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Person() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param name The new value for name
   * @param age The new value for age
   * @param height The new value for height
   * @param isEmployed The new value for isEmployed
   * @param address The new value for address
   * @param phoneNumbers The new value for phoneNumbers
   * @param salary The new value for salary
   * @param birthDate The new value for birthDate
   * @param skills The new value for skills
   */
  public Person(java.lang.Integer id, java.lang.CharSequence name, java.lang.Integer age, java.lang.Float height, java.lang.Boolean isEmployed, java.lang.CharSequence address, java.util.List<java.lang.CharSequence> phoneNumbers, java.lang.Float salary, com.javalearning.person.Date birthDate, java.util.Map<java.lang.CharSequence,java.lang.CharSequence> skills) {
    this.id = id;
    this.name = name;
    this.age = age;
    this.height = height;
    this.isEmployed = isEmployed;
    this.address = address;
    this.phoneNumbers = phoneNumbers;
    this.salary = salary;
    this.birthDate = birthDate;
    this.skills = skills;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return name;
    case 2: return age;
    case 3: return height;
    case 4: return isEmployed;
    case 5: return address;
    case 6: return phoneNumbers;
    case 7: return salary;
    case 8: return birthDate;
    case 9: return skills;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: name = (java.lang.CharSequence)value$; break;
    case 2: age = (java.lang.Integer)value$; break;
    case 3: height = (java.lang.Float)value$; break;
    case 4: isEmployed = (java.lang.Boolean)value$; break;
    case 5: address = (java.lang.CharSequence)value$; break;
    case 6: phoneNumbers = (java.util.List<java.lang.CharSequence>)value$; break;
    case 7: salary = (java.lang.Float)value$; break;
    case 8: birthDate = (com.javalearning.person.Date)value$; break;
    case 9: skills = (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public int getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(int value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'age' field.
   * @return The value of the 'age' field.
   */
  public int getAge() {
    return age;
  }


  /**
   * Sets the value of the 'age' field.
   * @param value the value to set.
   */
  public void setAge(int value) {
    this.age = value;
  }

  /**
   * Gets the value of the 'height' field.
   * @return The value of the 'height' field.
   */
  public float getHeight() {
    return height;
  }


  /**
   * Sets the value of the 'height' field.
   * @param value the value to set.
   */
  public void setHeight(float value) {
    this.height = value;
  }

  /**
   * Gets the value of the 'isEmployed' field.
   * @return The value of the 'isEmployed' field.
   */
  public boolean getIsEmployed() {
    return isEmployed;
  }


  /**
   * Sets the value of the 'isEmployed' field.
   * @param value the value to set.
   */
  public void setIsEmployed(boolean value) {
    this.isEmployed = value;
  }

  /**
   * Gets the value of the 'address' field.
   * @return The value of the 'address' field.
   */
  public java.lang.CharSequence getAddress() {
    return address;
  }


  /**
   * Sets the value of the 'address' field.
   * @param value the value to set.
   */
  public void setAddress(java.lang.CharSequence value) {
    this.address = value;
  }

  /**
   * Gets the value of the 'phoneNumbers' field.
   * @return The value of the 'phoneNumbers' field.
   */
  public java.util.List<java.lang.CharSequence> getPhoneNumbers() {
    return phoneNumbers;
  }


  /**
   * Sets the value of the 'phoneNumbers' field.
   * @param value the value to set.
   */
  public void setPhoneNumbers(java.util.List<java.lang.CharSequence> value) {
    this.phoneNumbers = value;
  }

  /**
   * Gets the value of the 'salary' field.
   * @return The value of the 'salary' field.
   */
  public java.lang.Float getSalary() {
    return salary;
  }


  /**
   * Sets the value of the 'salary' field.
   * @param value the value to set.
   */
  public void setSalary(java.lang.Float value) {
    this.salary = value;
  }

  /**
   * Gets the value of the 'birthDate' field.
   * @return The value of the 'birthDate' field.
   */
  public com.javalearning.person.Date getBirthDate() {
    return birthDate;
  }


  /**
   * Sets the value of the 'birthDate' field.
   * @param value the value to set.
   */
  public void setBirthDate(com.javalearning.person.Date value) {
    this.birthDate = value;
  }

  /**
   * Gets the value of the 'skills' field.
   * @return The value of the 'skills' field.
   */
  public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getSkills() {
    return skills;
  }


  /**
   * Sets the value of the 'skills' field.
   * @param value the value to set.
   */
  public void setSkills(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
    this.skills = value;
  }

  /**
   * Creates a new Person RecordBuilder.
   * @return A new Person RecordBuilder
   */
  public static com.javalearning.person.Person.Builder newBuilder() {
    return new com.javalearning.person.Person.Builder();
  }

  /**
   * Creates a new Person RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Person RecordBuilder
   */
  public static com.javalearning.person.Person.Builder newBuilder(com.javalearning.person.Person.Builder other) {
    if (other == null) {
      return new com.javalearning.person.Person.Builder();
    } else {
      return new com.javalearning.person.Person.Builder(other);
    }
  }

  /**
   * Creates a new Person RecordBuilder by copying an existing Person instance.
   * @param other The existing instance to copy.
   * @return A new Person RecordBuilder
   */
  public static com.javalearning.person.Person.Builder newBuilder(com.javalearning.person.Person other) {
    if (other == null) {
      return new com.javalearning.person.Person.Builder();
    } else {
      return new com.javalearning.person.Person.Builder(other);
    }
  }

  /**
   * RecordBuilder for Person instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Person>
    implements org.apache.avro.data.RecordBuilder<Person> {

    private int id;
    private java.lang.CharSequence name;
    private int age;
    private float height;
    private boolean isEmployed;
    private java.lang.CharSequence address;
    private java.util.List<java.lang.CharSequence> phoneNumbers;
    private java.lang.Float salary;
    private com.javalearning.person.Date birthDate;
    private com.javalearning.person.Date.Builder birthDateBuilder;
    private java.util.Map<java.lang.CharSequence,java.lang.CharSequence> skills;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.javalearning.person.Person.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.age)) {
        this.age = data().deepCopy(fields()[2].schema(), other.age);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.height)) {
        this.height = data().deepCopy(fields()[3].schema(), other.height);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.isEmployed)) {
        this.isEmployed = data().deepCopy(fields()[4].schema(), other.isEmployed);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.address)) {
        this.address = data().deepCopy(fields()[5].schema(), other.address);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.phoneNumbers)) {
        this.phoneNumbers = data().deepCopy(fields()[6].schema(), other.phoneNumbers);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.salary)) {
        this.salary = data().deepCopy(fields()[7].schema(), other.salary);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.birthDate)) {
        this.birthDate = data().deepCopy(fields()[8].schema(), other.birthDate);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (other.hasBirthDateBuilder()) {
        this.birthDateBuilder = com.javalearning.person.Date.newBuilder(other.getBirthDateBuilder());
      }
      if (isValidValue(fields()[9], other.skills)) {
        this.skills = data().deepCopy(fields()[9].schema(), other.skills);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
    }

    /**
     * Creates a Builder by copying an existing Person instance
     * @param other The existing instance to copy.
     */
    private Builder(com.javalearning.person.Person other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.age)) {
        this.age = data().deepCopy(fields()[2].schema(), other.age);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.height)) {
        this.height = data().deepCopy(fields()[3].schema(), other.height);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.isEmployed)) {
        this.isEmployed = data().deepCopy(fields()[4].schema(), other.isEmployed);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.address)) {
        this.address = data().deepCopy(fields()[5].schema(), other.address);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.phoneNumbers)) {
        this.phoneNumbers = data().deepCopy(fields()[6].schema(), other.phoneNumbers);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.salary)) {
        this.salary = data().deepCopy(fields()[7].schema(), other.salary);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.birthDate)) {
        this.birthDate = data().deepCopy(fields()[8].schema(), other.birthDate);
        fieldSetFlags()[8] = true;
      }
      this.birthDateBuilder = null;
      if (isValidValue(fields()[9], other.skills)) {
        this.skills = data().deepCopy(fields()[9].schema(), other.skills);
        fieldSetFlags()[9] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public int getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.javalearning.person.Person.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.javalearning.person.Person.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.javalearning.person.Person.Builder setName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.javalearning.person.Person.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'age' field.
      * @return The value.
      */
    public int getAge() {
      return age;
    }


    /**
      * Sets the value of the 'age' field.
      * @param value The value of 'age'.
      * @return This builder.
      */
    public com.javalearning.person.Person.Builder setAge(int value) {
      validate(fields()[2], value);
      this.age = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'age' field has been set.
      * @return True if the 'age' field has been set, false otherwise.
      */
    public boolean hasAge() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'age' field.
      * @return This builder.
      */
    public com.javalearning.person.Person.Builder clearAge() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'height' field.
      * @return The value.
      */
    public float getHeight() {
      return height;
    }


    /**
      * Sets the value of the 'height' field.
      * @param value The value of 'height'.
      * @return This builder.
      */
    public com.javalearning.person.Person.Builder setHeight(float value) {
      validate(fields()[3], value);
      this.height = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'height' field has been set.
      * @return True if the 'height' field has been set, false otherwise.
      */
    public boolean hasHeight() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'height' field.
      * @return This builder.
      */
    public com.javalearning.person.Person.Builder clearHeight() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'isEmployed' field.
      * @return The value.
      */
    public boolean getIsEmployed() {
      return isEmployed;
    }


    /**
      * Sets the value of the 'isEmployed' field.
      * @param value The value of 'isEmployed'.
      * @return This builder.
      */
    public com.javalearning.person.Person.Builder setIsEmployed(boolean value) {
      validate(fields()[4], value);
      this.isEmployed = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'isEmployed' field has been set.
      * @return True if the 'isEmployed' field has been set, false otherwise.
      */
    public boolean hasIsEmployed() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'isEmployed' field.
      * @return This builder.
      */
    public com.javalearning.person.Person.Builder clearIsEmployed() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'address' field.
      * @return The value.
      */
    public java.lang.CharSequence getAddress() {
      return address;
    }


    /**
      * Sets the value of the 'address' field.
      * @param value The value of 'address'.
      * @return This builder.
      */
    public com.javalearning.person.Person.Builder setAddress(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.address = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'address' field has been set.
      * @return True if the 'address' field has been set, false otherwise.
      */
    public boolean hasAddress() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'address' field.
      * @return This builder.
      */
    public com.javalearning.person.Person.Builder clearAddress() {
      address = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'phoneNumbers' field.
      * @return The value.
      */
    public java.util.List<java.lang.CharSequence> getPhoneNumbers() {
      return phoneNumbers;
    }


    /**
      * Sets the value of the 'phoneNumbers' field.
      * @param value The value of 'phoneNumbers'.
      * @return This builder.
      */
    public com.javalearning.person.Person.Builder setPhoneNumbers(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[6], value);
      this.phoneNumbers = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'phoneNumbers' field has been set.
      * @return True if the 'phoneNumbers' field has been set, false otherwise.
      */
    public boolean hasPhoneNumbers() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'phoneNumbers' field.
      * @return This builder.
      */
    public com.javalearning.person.Person.Builder clearPhoneNumbers() {
      phoneNumbers = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'salary' field.
      * @return The value.
      */
    public java.lang.Float getSalary() {
      return salary;
    }


    /**
      * Sets the value of the 'salary' field.
      * @param value The value of 'salary'.
      * @return This builder.
      */
    public com.javalearning.person.Person.Builder setSalary(java.lang.Float value) {
      validate(fields()[7], value);
      this.salary = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'salary' field has been set.
      * @return True if the 'salary' field has been set, false otherwise.
      */
    public boolean hasSalary() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'salary' field.
      * @return This builder.
      */
    public com.javalearning.person.Person.Builder clearSalary() {
      salary = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'birthDate' field.
      * @return The value.
      */
    public com.javalearning.person.Date getBirthDate() {
      return birthDate;
    }


    /**
      * Sets the value of the 'birthDate' field.
      * @param value The value of 'birthDate'.
      * @return This builder.
      */
    public com.javalearning.person.Person.Builder setBirthDate(com.javalearning.person.Date value) {
      validate(fields()[8], value);
      this.birthDateBuilder = null;
      this.birthDate = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'birthDate' field has been set.
      * @return True if the 'birthDate' field has been set, false otherwise.
      */
    public boolean hasBirthDate() {
      return fieldSetFlags()[8];
    }

    /**
     * Gets the Builder instance for the 'birthDate' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.javalearning.person.Date.Builder getBirthDateBuilder() {
      if (birthDateBuilder == null) {
        if (hasBirthDate()) {
          setBirthDateBuilder(com.javalearning.person.Date.newBuilder(birthDate));
        } else {
          setBirthDateBuilder(com.javalearning.person.Date.newBuilder());
        }
      }
      return birthDateBuilder;
    }

    /**
     * Sets the Builder instance for the 'birthDate' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.javalearning.person.Person.Builder setBirthDateBuilder(com.javalearning.person.Date.Builder value) {
      clearBirthDate();
      birthDateBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'birthDate' field has an active Builder instance
     * @return True if the 'birthDate' field has an active Builder instance
     */
    public boolean hasBirthDateBuilder() {
      return birthDateBuilder != null;
    }

    /**
      * Clears the value of the 'birthDate' field.
      * @return This builder.
      */
    public com.javalearning.person.Person.Builder clearBirthDate() {
      birthDate = null;
      birthDateBuilder = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'skills' field.
      * @return The value.
      */
    public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getSkills() {
      return skills;
    }


    /**
      * Sets the value of the 'skills' field.
      * @param value The value of 'skills'.
      * @return This builder.
      */
    public com.javalearning.person.Person.Builder setSkills(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
      validate(fields()[9], value);
      this.skills = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'skills' field has been set.
      * @return True if the 'skills' field has been set, false otherwise.
      */
    public boolean hasSkills() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'skills' field.
      * @return This builder.
      */
    public com.javalearning.person.Person.Builder clearSkills() {
      skills = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Person build() {
      try {
        Person record = new Person();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.age = fieldSetFlags()[2] ? this.age : (java.lang.Integer) defaultValue(fields()[2]);
        record.height = fieldSetFlags()[3] ? this.height : (java.lang.Float) defaultValue(fields()[3]);
        record.isEmployed = fieldSetFlags()[4] ? this.isEmployed : (java.lang.Boolean) defaultValue(fields()[4]);
        record.address = fieldSetFlags()[5] ? this.address : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.phoneNumbers = fieldSetFlags()[6] ? this.phoneNumbers : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[6]);
        record.salary = fieldSetFlags()[7] ? this.salary : (java.lang.Float) defaultValue(fields()[7]);
        if (birthDateBuilder != null) {
          try {
            record.birthDate = this.birthDateBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("birthDate"));
            throw e;
          }
        } else {
          record.birthDate = fieldSetFlags()[8] ? this.birthDate : (com.javalearning.person.Date) defaultValue(fields()[8]);
        }
        record.skills = fieldSetFlags()[9] ? this.skills : (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>) defaultValue(fields()[9]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Person>
    WRITER$ = (org.apache.avro.io.DatumWriter<Person>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Person>
    READER$ = (org.apache.avro.io.DatumReader<Person>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.id);

    out.writeString(this.name);

    out.writeInt(this.age);

    out.writeFloat(this.height);

    out.writeBoolean(this.isEmployed);

    out.writeString(this.address);

    long size0 = this.phoneNumbers.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.lang.CharSequence e0: this.phoneNumbers) {
      actualSize0++;
      out.startItem();
      out.writeString(e0);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

    if (this.salary == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeFloat(this.salary);
    }

    this.birthDate.customEncode(out);

    long size1 = this.skills.size();
    out.writeMapStart();
    out.setItemCount(size1);
    long actualSize1 = 0;
    for (java.util.Map.Entry<java.lang.CharSequence, java.lang.CharSequence> e1: this.skills.entrySet()) {
      actualSize1++;
      out.startItem();
      out.writeString(e1.getKey());
      java.lang.CharSequence v1 = e1.getValue();
      out.writeString(v1);
    }
    out.writeMapEnd();
    if (actualSize1 != size1)
      throw new java.util.ConcurrentModificationException("Map-size written was " + size1 + ", but element count was " + actualSize1 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readInt();

      this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);

      this.age = in.readInt();

      this.height = in.readFloat();

      this.isEmployed = in.readBoolean();

      this.address = in.readString(this.address instanceof Utf8 ? (Utf8)this.address : null);

      long size0 = in.readArrayStart();
      java.util.List<java.lang.CharSequence> a0 = this.phoneNumbers;
      if (a0 == null) {
        a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("phoneNumbers").schema());
        this.phoneNumbers = a0;
      } else a0.clear();
      SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
          e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
          a0.add(e0);
        }
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.salary = null;
      } else {
        this.salary = in.readFloat();
      }

      if (this.birthDate == null) {
        this.birthDate = new com.javalearning.person.Date();
      }
      this.birthDate.customDecode(in);

      long size1 = in.readMapStart();
      java.util.Map<java.lang.CharSequence,java.lang.CharSequence> m1 = this.skills; // Need fresh name due to limitation of macro system
      if (m1 == null) {
        m1 = new java.util.HashMap<java.lang.CharSequence,java.lang.CharSequence>((int)size1);
        this.skills = m1;
      } else m1.clear();
      for ( ; 0 < size1; size1 = in.mapNext()) {
        for ( ; size1 != 0; size1--) {
          java.lang.CharSequence k1 = null;
          k1 = in.readString(k1 instanceof Utf8 ? (Utf8)k1 : null);
          java.lang.CharSequence v1 = null;
          v1 = in.readString(v1 instanceof Utf8 ? (Utf8)v1 : null);
          m1.put(k1, v1);
        }
      }

    } else {
      for (int i = 0; i < 10; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readInt();
          break;

        case 1:
          this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
          break;

        case 2:
          this.age = in.readInt();
          break;

        case 3:
          this.height = in.readFloat();
          break;

        case 4:
          this.isEmployed = in.readBoolean();
          break;

        case 5:
          this.address = in.readString(this.address instanceof Utf8 ? (Utf8)this.address : null);
          break;

        case 6:
          long size0 = in.readArrayStart();
          java.util.List<java.lang.CharSequence> a0 = this.phoneNumbers;
          if (a0 == null) {
            a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("phoneNumbers").schema());
            this.phoneNumbers = a0;
          } else a0.clear();
          SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
              e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
              a0.add(e0);
            }
          }
          break;

        case 7:
          if (in.readIndex() != 1) {
            in.readNull();
            this.salary = null;
          } else {
            this.salary = in.readFloat();
          }
          break;

        case 8:
          if (this.birthDate == null) {
            this.birthDate = new com.javalearning.person.Date();
          }
          this.birthDate.customDecode(in);
          break;

        case 9:
          long size1 = in.readMapStart();
          java.util.Map<java.lang.CharSequence,java.lang.CharSequence> m1 = this.skills; // Need fresh name due to limitation of macro system
          if (m1 == null) {
            m1 = new java.util.HashMap<java.lang.CharSequence,java.lang.CharSequence>((int)size1);
            this.skills = m1;
          } else m1.clear();
          for ( ; 0 < size1; size1 = in.mapNext()) {
            for ( ; size1 != 0; size1--) {
              java.lang.CharSequence k1 = null;
              k1 = in.readString(k1 instanceof Utf8 ? (Utf8)k1 : null);
              java.lang.CharSequence v1 = null;
              v1 = in.readString(v1 instanceof Utf8 ? (Utf8)v1 : null);
              m1.put(k1, v1);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










